Neos:
  Flow:
    security:
      authentication:
        providers:
          'AnvilTokenProvider':
            provider: 'Langeland\AnvilUserInterface\Security\AnvilKeyProvider'
            token: 'Langeland\AnvilUserInterface\Security\AnvilKeyToken'
          'DefaultProvider':
            provider: 'Langeland\AnvilUserInterface\Security\PersistedUsernamePasswordProvider'
            token: 'Langeland\AnvilUserInterface\Security\UsernamePassword'
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
                '@package': 'Langeland.AnvilUserInterface'
                '@controller': 'User'
                '@action': 'login'
    session:

      # Specifies the number of seconds a user must be idle before the session
      # automatically expires. If set to "0", a session will never expire
      # automatically.
      inactivityTimeout: 0

      # A specific name for the session, used in the session cookie.
      # The session name must be alphanumerical and must contain at least one
      # character – not only numbers.
      name: 'Anvil_Session'

      # Configuration for handling of expired sessions
      garbageCollection:

        # The probability in percent of a session shutdown triggering a garbage
        # collection which removes expired session data from other sessions.
        #
        # Examples:
        #    1    (would be a 1% chance to clean up)
        #   20    (would be a 20% chance to clean up)
        #    0.42 (would be a 0.42 % chance to clean up)
        probability: 0.1





Langeland:
  AnvilUserInterface:
    Authentication:
      passwords:
        toemmerstikket: 'Tømmerstikket'
        raabaandsknob: 'Råbåndsknob'
        dobbelt_halvstik: 'Dobbelt halvstik'
        dobbelt_halvstik_om_egen_part: 'Dobbelt halvstik om egen part'
        paelestik: 'Pælestik'
        kvaelerstikket: 'Kvælerstikket'
        flagknob: 'Flagknob'
        sommerfugleknob: 'Sommerfugleknob'
        dobbelt_ottetalsknob: 'Dobbelt ottetalsknob'
        dobbelt_flagknob: 'Dobbelt flagknob'
