<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20181201091116 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_badge DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_badge ADD identifier VARCHAR(255) NOT NULL, ADD user VARCHAR(255) DEFAULT NULL, ADD createdat DATETIME NOT NULL, ADD modifiedat DATETIME NOT NULL, ADD startedat DATETIME NOT NULL, ADD addeddays INT NOT NULL, DROP persistence_object_identifier');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_badge ADD CONSTRAINT FK_3B125CE18D93D649 FOREIGN KEY (user) REFERENCES langeland_anvilcore_domain_model_user (identifier)');
        $this->addSql('CREATE INDEX IDX_3B125CE18D93D649 ON langeland_anvilcore_domain_model_badge (user)');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_badge ADD PRIMARY KEY (identifier)');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_user RENAME INDEX idx_d5bc94f16dc044c5 TO IDX_D5BC94F1DCBB0C53');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_badge DROP FOREIGN KEY FK_3B125CE18D93D649');
        $this->addSql('DROP INDEX IDX_3B125CE18D93D649 ON langeland_anvilcore_domain_model_badge');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_badge DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_badge ADD persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8mb4_unicode_ci, DROP identifier, DROP user, DROP createdat, DROP modifiedat, DROP startedat, DROP addeddays');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_badge ADD PRIMARY KEY (persistence_object_identifier)');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_user RENAME INDEX idx_d5bc94f1dcbb0c53 TO IDX_D5BC94F16DC044C5');
    }
}