<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20181130143253 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE langeland_anvilcore_domain_model_badge (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE langeland_anvilcore_domain_model_unit (code INT NOT NULL, name VARCHAR(255) NOT NULL, street VARCHAR(255) DEFAULT NULL, number INT DEFAULT NULL, zipcode VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(code)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE langeland_anvilcore_domain_model_user (identifier VARCHAR(255) NOT NULL, `unit` INT DEFAULT NULL, displayname VARCHAR(255) NOT NULL, INDEX IDX_D5BC94F16DC044C5 (`unit`), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE langeland_anvilcore_domain_model_user_accounts_join (anvilcore_user VARCHAR(255) NOT NULL, flow_security_account VARCHAR(40) NOT NULL, INDEX IDX_B3DEF0C84636A8F3 (anvilcore_user), UNIQUE INDEX UNIQ_B3DEF0C858842EFC (flow_security_account), PRIMARY KEY(anvilcore_user, flow_security_account)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_user ADD CONSTRAINT FK_D5BC94F16DC044C5 FOREIGN KEY (`unit`) REFERENCES langeland_anvilcore_domain_model_unit (code)');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_user_accounts_join ADD CONSTRAINT FK_B3DEF0C84636A8F3 FOREIGN KEY (anvilcore_user) REFERENCES langeland_anvilcore_domain_model_user (identifier)');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_user_accounts_join ADD CONSTRAINT FK_B3DEF0C858842EFC FOREIGN KEY (flow_security_account) REFERENCES neos_flow_security_account (persistence_object_identifier) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE neos_flow_resourcemanagement_persistentresource RENAME INDEX idx_35dc14f03332102a TO IDX_6954B1F63332102A');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_user DROP FOREIGN KEY FK_D5BC94F16DC044C5');
        $this->addSql('ALTER TABLE langeland_anvilcore_domain_model_user_accounts_join DROP FOREIGN KEY FK_B3DEF0C84636A8F3');
        $this->addSql('DROP TABLE langeland_anvilcore_domain_model_badge');
        $this->addSql('DROP TABLE langeland_anvilcore_domain_model_unit');
        $this->addSql('DROP TABLE langeland_anvilcore_domain_model_user');
        $this->addSql('DROP TABLE langeland_anvilcore_domain_model_user_accounts_join');
        $this->addSql('ALTER TABLE neos_flow_resourcemanagement_persistentresource RENAME INDEX idx_6954b1f63332102a TO IDX_35DC14F03332102A');
    }
}