##
# Anvil subroutes
#

- name: 'Anvil User Interface'
  uriPattern: 'ui/<AnvilUserInterfaceSubroutes>'
  defaults:
    '@package': 'Langeland.AnvilUserInterface'
    '@format': 'html'
  subRoutes:
    'AnvilUserInterfaceSubroutes':
      package: 'Langeland.AnvilUserInterface'

-
  name: 'index'
  uriPattern: ''
  defaults:
    '@package': 'Langeland.AnvilUserInterface'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true